### Librerie

In [ ]:
import pandas as pd
import requests
from datetime import datetime
from pathlib import Path

In [ ]:
def season_folder(start_year: int) -> str:
    # 1999 -> "9900", 2000 -> "0001", 2023 -> "2324"
    return f"{start_year % 100:02d}{(start_year + 1) % 100:02d}"

campionati = {}

for start_year in range(1993, 2025):  
    stagione = season_folder(start_year)
    url = f"https://www.football-data.co.uk/mmz4281/{stagione}/I1.csv"
    try:
        df = pd.read_csv(url)
        campionati[stagione] = df
        print("Scaricata:", stagione, "->", start_year, "/", start_year + 1)
    except Exception as e:
        print("Non trovata:", stagione, "-", e.__class__.__name__)

Scaricata: 9394 -> 1993 / 1994
Scaricata: 9495 -> 1994 / 1995
Scaricata: 9596 -> 1995 / 1996
Scaricata: 9697 -> 1996 / 1997
Scaricata: 9798 -> 1997 / 1998
Scaricata: 9899 -> 1998 / 1999
Scaricata: 9900 -> 1999 / 2000
Scaricata: 0001 -> 2000 / 2001
Scaricata: 0102 -> 2001 / 2002
Scaricata: 0203 -> 2002 / 2003
Non trovata: 0304 - ParserError
Non trovata: 0405 - ParserError
Scaricata: 0506 -> 2005 / 2006
Scaricata: 0607 -> 2006 / 2007
Scaricata: 0708 -> 2007 / 2008
Scaricata: 0809 -> 2008 / 2009
Scaricata: 0910 -> 2009 / 2010
Scaricata: 1011 -> 2010 / 2011
Scaricata: 1112 -> 2011 / 2012
Scaricata: 1213 -> 2012 / 2013
Scaricata: 1314 -> 2013 / 2014
Scaricata: 1415 -> 2014 / 2015
Scaricata: 1516 -> 2015 / 2016
Scaricata: 1617 -> 2016 / 2017
Scaricata: 1718 -> 2017 / 2018
Scaricata: 1819 -> 2018 / 2019
Scaricata: 1920 -> 2019 / 2020
Scaricata: 2021 -> 2020 / 2021
Scaricata: 2122 -> 2021 / 2022
Scaricata: 2223 -> 2022 / 2023
Scaricata: 2324 -> 2023 / 2024
Scaricata: 2425 -> 2024 / 2025


le stagioni 0304 e 0405 perche non me le riesce a parsare automanticamente il csv, le carico manualmente e le aggiungo al dizionario in un secondo momento

In [6]:
print(campionati.keys())

dict_keys(['9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324', '2425'])


Funzione fatta dal chattino perche non avevo voglia di perdere tempo mi serve a parsare i due campionati che rompono le scatole. Il problema è che c'erano delle virgole di troppo 

In [ ]:
def read_fixed_csv(path: str) -> pd.DataFrame:
    path = Path(path)
    fixed_path = path.with_name(path.stem + "_fixed.csv")

    with path.open("r", encoding="utf-8", errors="replace") as fin, \
         fixed_path.open("w", encoding="utf-8", newline="") as fout:
        for line in fin:
            # rimuove spazi + newline, poi toglie eventuali virgole finali
            cleaned = line.rstrip("\n\r").rstrip()
            cleaned = cleaned.rstrip(",")
            fout.write(cleaned + "\n")

    # ora le colonne saranno coerenti
    df = pd.read_csv(fixed_path)
    return df

df_0304 = read_fixed_csv(r"D:\- Davide\Desktop\statsXserieA\data\I1(3).csv")
df_0405 = read_fixed_csv(r"D:\- Davide\Desktop\statsXserieA\data\I1(4).csv")
print(df_0304.head())
print(df_0405.head())

  Div      Date  HomeTeam   AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  ...  \
0  I1  30/08/03   Reggina  Sampdoria     2     2   D     2     0   H  ...   
1  I1  31/08/03   Bologna      Parma     2     2   D     1     1   D  ...   
2  I1  31/08/03   Brescia     Chievo     1     1   D     0     1   A  ...   
3  I1  31/08/03     Inter     Modena     2     0   H     0     0   D  ...   
4  I1  31/08/03  Juventus     Empoli     5     1   H     1     0   H  ...   

   B365<2.5  GBAHH  GBAHA  GBAH  LBAHH  LBAHA  LBAH  B365AHH  B365AHA  B365AH  
0      1.83   2.00   1.80 -0.25   2.05   1.80 -0.25    2.075    1.825   -0.25  
1      1.80   2.10   1.75 -0.25   2.10   1.75 -0.25    1.750    2.150    0.00  
2      1.72   2.05   1.77 -0.25   2.10   1.75 -0.25    1.750    2.150    0.00  
3      1.90   1.85   1.95 -1.50   1.90   1.95 -1.50    1.925    1.975   -1.50  
4      2.00   1.85   1.95 -1.50   1.85   2.00 -1.50    1.875    2.025   -1.50  

[5 rows x 44 columns]
  Div      Date  HomeTeam  AwayTea

In [ ]:
"""
Aggiorno il dizionario con i due dataframe dei due campionati mancanti

"""

campionati.update({"0304":df_0304})
campionati.update({"0405":df_0405})


In [ ]:
#Controllo che ora ho tutta la base dati, guardo che le chiavi del dizionario
print(campionati.keys())

dict_keys(['9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324', '2425', '0304', '0405'])


In [ ]:
def parseDateSafe(x):

    for fmt in ("%d/%m/%Y", "%d/%m/%y", "%Y-%m-%d", "%d-%m-%Y"):
        try:
            return datetime.strptime(str(x), fmt)
        except:
            continue
    return pd.NaT

def matchesBuilder(df: pd.DataFrame) -> pd.DataFrame:
    """
    In: dataframe
    Out: dataframe

    Pulisco il dataset che avevo in entrata andando a fare una feature selection di cio che serve a me
    """
   
    colonneDaMappare = {
        "HomeTeam": "HomeTeam",
        "AwayTeam": "AwayTeam",
        "FTHG": "FTHG",
        "FTAG": "FTAG",
        "Date": "Date",
    }

    out = df[list(colonneDaMappare.keys())].copy()

   # ho dovuto aggiungere la funzione parseDateSafe per evitare problemi tra formati 
    out["Date"] = out["Date"].apply(parseDateSafe)

    out = out.sort_values(["Date"], na_position="last").reset_index(drop=True)
    
    out["FTHG"] = pd.to_numeric(out["FTHG"], errors="coerce")
    out["FTAG"] = pd.to_numeric(out["FTAG"], errors="coerce")

    
    out = out.dropna(subset=["HomeTeam", "AwayTeam", "FTHG", "FTAG"]).reset_index(drop=True)

    return out

def classificaBuilder(df_season: pd.DataFrame):
    """
    In: dataframe
    Out: variabili winter,final che poi andro appaire in un secondo momento per creare il df finale 
    
    """
    m = matchesBuilder(df_season)

    teams = pd.unique(pd.concat([m["HomeTeam"], m["AwayTeam"]], ignore_index=True))
    n_teams = len(teams)
    half_games = n_teams - 1

    table = pd.DataFrame(index=teams, data={"GP": 0, "GF": 0, "GA": 0, "Pts": 0})
    winter = None

    for _, r in m.iterrows():
        h, a = r["HomeTeam"], r["AwayTeam"]
        hg, ag = int(r["FTHG"]), int(r["FTAG"])

        table.loc[[h, a], "GP"] += 1
        table.loc[h, "GF"] += hg
        table.loc[h, "GA"] += ag
        table.loc[a, "GF"] += ag
        table.loc[a, "GA"] += hg

        if hg > ag:
            table.loc[h, "Pts"] += 3
        elif hg < ag:
            table.loc[a, "Pts"] += 3
        else:
            table.loc[[h, a], "Pts"] += 1

        if winter is None and table["GP"].min() >= half_games:
            tmp = table.copy()
            tmp["GD"] = tmp["GF"] - tmp["GA"]
            winter = tmp.sort_values(["Pts", "GD", "GF"], ascending=False).index[0]

    tmp = table.copy()
    tmp["GD"] = tmp["GF"] - tmp["GA"]
    final = tmp.sort_values(["Pts", "GD", "GF"], ascending=False).index[0]

    return winter, final

In [23]:
results = []

for season, df in campionati.items():
    try:
        winter, final = classificaBuilder(df)
        results.append((season, winter, final, winter == final))
    except Exception as e:
        results.append((season, None, None, None))
        print("Errore su", season, ":", repr(e))

res = pd.DataFrame(results, columns=["season", "winter", "final", "same"]).sort_values("season")
print(res)

print("P(scudetto | campione d'inverno) =", res["same"].mean())



   season      winter     final   same
7    0001        Roma      Roma   True
8    0102        Roma  Juventus  False
9    0203       Milan  Juventus  False
30   0304        Roma     Milan  False
31   0405    Juventus  Juventus   True
10   0506    Juventus  Juventus   True
11   0607       Inter     Inter   True
12   0708       Inter     Inter   True
13   0809       Inter     Inter   True
14   0910       Inter     Inter   True
15   1011       Milan     Milan   True
16   1112    Juventus  Juventus   True
17   1213    Juventus  Juventus   True
18   1314    Juventus  Juventus   True
19   1415    Juventus  Juventus   True
20   1516      Napoli  Juventus  False
21   1617    Juventus  Juventus   True
22   1718      Napoli  Juventus  False
23   1819    Juventus  Juventus   True
24   1920    Juventus  Juventus   True
25   2021       Milan     Inter  False
26   2122       Inter     Milan  False
27   2223      Napoli    Napoli   True
28   2324       Inter     Inter   True
29   2425      Napoli    

In [24]:
print("P(scudetto | campione d'inverno) =", res["same"].mean())

P(scudetto | campione d'inverno) = 0.71875
